msm: camera: flash: move `isEnable` variable outside of soc header
It causes duplicate symbol issue:
ld.lld: error: duplicate symbol: isEnable
>>> defined at lge_regulator_mode_change.h:18 (../../../../../../kernel/lge/sdm845/include/soc/qcom/lge/lge_regulator_mode_change.h:18)
>>>            drivers/built-in.o:(isEnable)
>>> defined at lge_regulator_mode_change.h:18 (../../../../../../kernel/lge/sdm845/include/soc/qcom/lge/lge_regulator_mode_change.h:18)
>>>            techpack/built-in.o:(.bss+0x54420)

This variable only ever gets touched within this file, so keep it
there.

Change-Id: I6056da110499ff6b2b236d59b1ef5227f1e7b64c
Signed-off-by: Han Sol Jin <hansol@hansol.ca>